<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <SkipMicrosoftMauiResizetizer>true</SkipMicrosoftMauiResizetizer>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="6.0.4" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
        <PackageReference Include="xunit" Version="2.9.3" />
        <PackageReference Include="xunit.runner.visualstudio" Version="3.0.2" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="YamlDotNet" Version="16.3.0" />
    </ItemGroup>

    <ItemGroup>
        <Compile Include="..\..\src\LoRAMancer.App\Models\*.cs" Link="Models\%(Filename)%(Extension)" />
        <Compile Include="..\..\src\LoRAMancer.App\Engines\*.cs" Link="Engines\%(Filename)%(Extension)" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\LoRAMancer.PluginSdk\LoRAMancer.PluginSdk.csproj" />
    </ItemGroup>

</Project>